In [1]:
import numpy as np

In [25]:
#arange komutu ile 0 dan başlayarak 5 değerine kadar bir array oluştur
a = np.arange(6)
a2 = a[np.newaxis, 1:3]
a3 = a2[np.newaxis, 0]
#shape fonksiyonu ile array in düzlemlerin büyüklüğünü yazdır.
a2.shape

(1, 2)

In [26]:
print(a)
print(a2)
print(a3)

[0 1 2 3 4 5]
[[1 2]]
[[1 2]]


Array: Merkezi veri saklama birimimizdir.
Basitçe adlandırmak gerekirse bir veri düzlemidir.

In [7]:
a = np.array([[1, 2, 3, 4, 5, 6],[5,6,8,9,7,1],[5,8,6,2,18,6]])

In [8]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  8,  9,  7,  1],
       [ 5,  8,  6,  2, 18,  6]])

In [9]:
myList = [0,5,9,5,2,1,8,63,2,1,8,9,2,3,5,8,74,6,2]

myList[5]
#indexler sayılmaya 0 dan başlar.



1

Arrayler; n boyutlu olmak üzerine şekillenebilir, matrix ve vector olabilir.

In [28]:
a = np.array([[0., 0., 0.],
 [1., 1., 1.]])

In [29]:
a

array([[0., 0., 0.],
       [1., 1., 1.]])

In [35]:
#zeros fonksiyonunu çalıştırken matrix büyüklüğünü ([]) içindeki değerlerle ayarlayabiliriz.
print(np.zeros([3,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
#The function empty creates an array whose initial content
#is random and depends on the state of the memory.
print(np.empty([6,8]))
print(np.zeros([6,8]))

[[4.64040571e-310 0.00000000e+000 6.76392678e-310 6.76392677e-310
  6.76399008e-310 6.76392678e-310 6.76399007e-310 6.76399008e-310]
 [6.76399005e-310 6.76399014e-310 6.76398998e-310 6.76399011e-310
  6.76399003e-310 6.76396890e-310 6.76392677e-310 6.76399003e-310]
 [6.76398999e-310 6.76399003e-310 6.76392677e-310 6.76398982e-310
  6.76399008e-310 6.76392678e-310 6.76399007e-310 6.76392677e-310]
 [6.76392677e-310 6.76399013e-310 6.76399008e-310 6.76399013e-310
  6.76399013e-310 6.76399013e-310 6.76392677e-310 6.76399014e-310]
 [6.76399007e-310 6.76399014e-310 6.76392677e-310 6.76399014e-310
  6.76399008e-310 6.76392677e-310 6.76399007e-310 6.76392677e-310]
 [6.76398998e-310 6.76399008e-310 6.76399008e-310 6.76392678e-310
  6.76392678e-310 6.76399008e-310 6.76392677e-310 6.76399007e-310]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [45]:
print(np.arange(9))

[0 1 2 3 4 5 6 7 8]


In [48]:
"""linspace fonksiyonu başlangıç, son değerleri arasındaki değerleri
verilen sayı kadar eşit parçaya bölerek bir array oluşturur."""
np.linspace(0, 10000, num=250)

array([    0.        ,    40.16064257,    80.32128514,   120.48192771,
         160.64257028,   200.80321285,   240.96385542,   281.12449799,
         321.28514056,   361.44578313,   401.6064257 ,   441.76706827,
         481.92771084,   522.08835341,   562.24899598,   602.40963855,
         642.57028112,   682.73092369,   722.89156627,   763.05220884,
         803.21285141,   843.37349398,   883.53413655,   923.69477912,
         963.85542169,  1004.01606426,  1044.17670683,  1084.3373494 ,
        1124.49799197,  1164.65863454,  1204.81927711,  1244.97991968,
        1285.14056225,  1325.30120482,  1365.46184739,  1405.62248996,
        1445.78313253,  1485.9437751 ,  1526.10441767,  1566.26506024,
        1606.42570281,  1646.58634538,  1686.74698795,  1726.90763052,
        1767.06827309,  1807.22891566,  1847.38955823,  1887.5502008 ,
        1927.71084337,  1967.87148594,  2008.03212851,  2048.19277108,
        2088.35341365,  2128.51405622,  2168.6746988 ,  2208.83534137,
      

In [50]:
"""arraylerin içerisindeki değerlerin veri tipini değiştirmek
için dtype parametresini kullanabiliriz"""
x = np.ones([5,5], dtype=np.int64)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:

arr = np.array([2, 1, 5,5,5,5,6,8,8,77,8,2,1,56,5, 3, 7, 4, 6, 8])

np.sort(arr)



array([ 1,  1,  2,  2,  3,  4,  5,  5,  5,  5,  5,  6,  6,  7,  8,  8,  8,
        8, 56, 77])

In [53]:
"""argsort, which is an indirect sort along a specified axis,

lexsort, which is an indirect stable sort on multiple keys,

searchsorted, which will find elements in a sorted array, and

partition, which is a partial sort."""



'argsort, which is an indirect sort along a specified axis,\n\nlexsort, which is an indirect stable sort on multiple keys,\n\nsearchsorted, which will find elements in a sorted array, and\n\npartition, which is a partial sort.'

In [60]:
a = np.array([1, 2, 3, 4])
b = np.array([4,5, 6, 7])

In [61]:
"""concatenate ifadesi verilen birkaç matrixi
 birleştirerek, varolan değerleri matrix başı kaç defa varsa toplamı kadar yazdırır"""
np.concatenate((a,b))

array([1, 2, 3, 4, 4, 5, 6, 7])

In [62]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [66]:
np.concatenate((x, y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [77]:
array_example.ndim

3

In [78]:
array_example.size

32

In [79]:
array_example.shape

(4, 2, 4)

In [84]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [81]:
b = a.reshape(3, 2)

In [82]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [85]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [95]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [97]:
a2 = a[np.newaxis, :]
a2.shape
a2

array([[1, 2, 3, 4, 5, 6]])

In [99]:
col_vector = a[:, np.newaxis]
col_vector.shape
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [101]:
b = np.expand_dims(a, axis=1)
b.shape
(6, 1)

(6, 1)

In [102]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [105]:
print(a[a < 12])

[ 1  2  3  4  5  6  7  8  9 10 11]


In [106]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [108]:
divisible_by_2 = a[a%2==1]
print(divisible_by_2)

[ 1  3  5  7  9 11]


In [109]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [114]:
five_up = (a <= 5)
print(five_up)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [115]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [121]:
""" çıktı verilen ilk değer dış matrixteki yerini,
 ikinci değer de sütun numarasını vermektedir"""
b = np.nonzero(a >5)
print(b)

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))


In [122]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)



(1, 1)
(1, 2)
(1, 3)
(2, 0)
(2, 1)
(2, 2)
(2, 3)


In [123]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [125]:

arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [126]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [127]:
#vertical stacking
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [128]:
#horizontal stacking
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [129]:
x = np.arange(1, 25).reshape(2, 12)

In [130]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [131]:
"""horizontal split verilen indexlere göre matrixleri eşit parçalara böler"""
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [132]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [133]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [135]:
b1 = a[0, 0:2]
b1

array([1, 2])

In [136]:
b1[0] = 99
b1

array([99,  2])

In [137]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
b2 = a.copy()

In [144]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [142]:
print(np.ones([1,2]))

[[1. 1.]]


In [145]:
data - ones

array([0, 1])

In [146]:
data * data

array([1, 4])

In [147]:
data / data

array([1., 1.])

In [174]:
#sum fonksiyonu matrix içerisindeki tüm itemleri toplar ve çıktı verir
a = np.array([[1,5,6,2,8],[8,9,6,2,8]])
c = 3


a*c

array([[ 3, 15, 18,  6, 24],
       [24, 27, 18,  6, 24]])

In [173]:
b = np.array([[8,6], [5, -2],[8,26]])
b

array([[ 8,  6],
       [ 5, -2],
       [ 8, 26]])

In [171]:
b.sum(axis=0)

array([21, 30])

In [172]:
b.sum(axis=1)

array([14,  3, 34])

In [175]:
"""axis = 0 sütunlar içerisinde operasyon yaparken
axis=1 satırlar içinde işlem yapar"""

'axis = 0 sütunlar içerisinde operasyon yaparken \naxis=1 satırlar içinde işlem yapar'

In [191]:
data = np.array([[1, 2],[15,-1]])
print(data)

data.max(axis=0)

[[ 1  2]
 [15 -1]]


array([15,  2])

In [188]:
data.min(axis=0)

array([ 1, -1])

In [190]:
data.sum(axis=1)

array([ 3, 14])

In [192]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [193]:
data[0,1]

2

In [195]:
data[1:2]

array([[3, 4]])

In [196]:
data[0:2, 0]

array([1, 3])

In [197]:
#axis=0 sütunları tarar, axis=1 satırları tarar

np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [199]:
rng = np.random.default_rng()
rng.random(3)

array([0.65193154, 0.91592204, 0.98627085])

In [209]:
x=0
while x<=3:
  print(rng.integers(500, size=(4, 2)))
  x=x+1

[[344 397]
 [  4 152]
 [ 23  88]
 [483 116]]
[[263 238]
 [ 78 371]
 [365 168]
 [141 212]]
[[197 288]
 [291 219]
 [ 82 448]
 [367 370]]
[[322 227]
 [422 335]
 [407  42]
 [312 226]]


In [ ]:
import pandas as pd

data_path =

In [210]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])


In [211]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [213]:
a.count("11")

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [214]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]
