In [1]:
import numpy as np


In [2]:
a = np.array([1,5,5,56,2,8,8,8,78,4,52,5,5,68,8,78,2,6])


unique_values, occurrence_count = np.unique(a, return_counts=True)
print(unique_values)
print(occurrence_count)

[ 1  2  4  5  6  8 52 56 68 78]
[1 2 1 4 1 4 1 1 1 2]


In [3]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [4]:
print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [5]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
print(indices)

[0 1 2]


In [9]:
print(occurrence_count)


[2 1 1]


# **Transposing and Reshaping**

In [18]:
data = np.array([[1,2,3,5],[8,4,5,6]])
print(data)

[[1 2 3 5]
 [8 4 5 6]]


In [19]:
data.reshape(2, 3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [21]:
data.reshape(8,1)

array([[1],
       [2],
       [3],
       [5],
       [8],
       [4],
       [5],
       [6]])

In [22]:
"""transpose ifadesi matrixte bulunan ifadeleri ve axisleri ters çevirir """
data.transpose()

array([[1, 8],
       [2, 4],
       [3, 5],
       [5, 6]])

In [23]:
data.T

array([[1, 8],
       [2, 4],
       [3, 5],
       [5, 6]])

In [24]:
!man --help

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, including manpages, you can run the 'unminimize'
command. You will still need to ensure the 'man-db' package is installed.


In [25]:
!man -h

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, including manpages, you can run the 'unminimize'
command. You will still need to ensure the 'man-db' package is installed.


# **reversing an array**

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
reversed_arr = np.flip(arr)

In [28]:
print(reversed_arr)

[8 7 6 5 4 3 2 1]


In [ ]:
# prompt: make a list and make the order backwards in python

# Create a list
my_list = [1, 2, 3, 4, 5]

# Reverse the order of the list
reversed_list = my_list[::-1]

# Print the reversed list
print(reversed_list)


In [29]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [30]:
sorted = np.flip(arr_2d)
print(sorted)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [31]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [32]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [36]:

print(arr_2d)
print(arr_2d[0][2])
print(arr_2d[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
[5 6 7 8]


In [37]:
arr_2d[1] = np.flip(arr_2d[1])



In [38]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [40]:
arr_2d[:2,1] = np.flip(arr_2d[:2,1])
print(arr_2d)

[[ 1  7  3  4]
 [ 8 10  6  5]
 [ 9  2 11 12]]


# **reshaping and flattening multidimensional arrays**

In [41]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [45]:
#matrisi tek boyut haline getirdik.
x.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
a1 = x.flatten() # tek bir satır haline geldi
a1[0] = 99 #

In [47]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [48]:
""" ravel komutu kullanıldığı zaman üzerinde işlem
 yapılan matrix de yapılan tüm işlemlerden etkilenir"""
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
